version: '3'

services:
 rabbitmq:
   image: rabbitmq:management
   container_name: rabbitmq
   environment:
     - RABBITMQ_DEFAULT_USER=RMQuser
     - RABBITMQ_DEFAULT_PASS=RMQP4ssw0rd#
   ports:
     - "5672:5672"
     - "15672:15672"

networks:
 default:
   driver: bridge
